# librarys

In [1]:
import matplotlib.pyplot as plt
import numpy as np 
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score , precision_score ,recall_score ,confusion_matrix
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn import preprocessing


# train & test reading file with pandas

In [2]:
df_test = pd.read_csv('./UNSW_NB15_testing-set.csv')
df_train = pd.read_csv('./UNSW_NB15_training-set.csv')

In [3]:
df_test.head()

id       dur proto service state  spkts  dpkts  sbytes  dbytes       rate  \
0   1       NaN   tcp       -   FIN      6      4     258     172  74.087490   
1   2  0.649902   tcp       -   FIN     14     38     734   42014  78.473372   
2   3  1.623129   tcp       -   FIN      8     16     364   13186  14.170161   
3   4  1.681642   tcp     ftp   FIN     12     12     628     770  13.677108   
4   5  0.449454   tcp       -   FIN     10      6     534     268  33.373826   

   ...  ct_dst_sport_ltm  ct_dst_src_ltm  is_ftp_login  ct_ftp_cmd  \
0  ...                 1               1             0           0   
1  ...                 1               2             0           0   
2  ...                 1               3             0           0   
3  ...                 1               3             1           1   
4  ...                 1              40             0           0   

   ct_flw_http_mthd  ct_src_ltm  ct_srv_dst  is_sm_ips_ports  attack_cat  \
0                 0           1           1                0      Normal   
1                 0           1           6                0      Normal   
2                 0           2           6                0      Normal   
3                 0           2           1                0      Normal   
4                 0           2          39                0      Normal   

   label  
0      0  
1      0  
2      0  
3      0  
4      0  

[5 rows x 45 columns]

In [4]:
df_train.head()

id       dur proto service state  spkts  dpkts  sbytes  dbytes  \
0   1       NaN   udp       -   INT      2      0     496       0   
1   2  0.000008   udp       -   INT      2      0    1762       0   
2   3  0.000005   udp       -   INT      2      0    1068       0   
3   4  0.000006   udp       -   INT      2      0     900       0   
4   5  0.000010   udp       -   INT      2      0    2126       0   

          rate  ...  ct_dst_sport_ltm  ct_dst_src_ltm  is_ftp_login  \
0   90909.0902  ...                 1               2             0   
1  125000.0003  ...                 1               2             0   
2  200000.0051  ...                 1               3             0   
3  166666.6608  ...                 1               3             0   
4  100000.0025  ...                 1               3             0   

   ct_ftp_cmd  ct_flw_http_mthd  ct_src_ltm  ct_srv_dst  is_sm_ips_ports  \
0           0                 0           1           2                0   
1           0                 0           1           2                0   
2           0                 0           1           3                0   
3           0                 0           2           3                0   
4           0                 0           2           3                0   

   attack_cat  label  
0      Normal      0  
1      Normal      0  
2      Normal      0  
3      Normal      0  
4      Normal      0  

[5 rows x 45 columns]

In [5]:
print(f"test shape is {df_test.shape}")
print(f"train shape is {df_train.shape}")

test shape is (175341, 45)
train shape is (82332, 45)


In [6]:
df_test.isnull().sum()

id                   0
dur                  1
proto                0
service              0
state                0
spkts                0
dpkts                0
sbytes               0
dbytes               0
rate                 0
sttl                 0
dttl                 0
sload                0
dload                0
sloss                0
dloss                0
sinpkt               0
dinpkt               0
sjit                 0
djit                 0
swin                 0
stcpb                0
dtcpb                0
dwin                 0
tcprtt               0
synack               0
ackdat               0
smean                0
dmean                0
trans_depth          0
response_body_len    0
ct_srv_src           0
ct_state_ttl         0
ct_dst_ltm           0
ct_src_dport_ltm     0
ct_dst_sport_ltm     0
ct_dst_src_ltm       0
is_ftp_login         0
ct_ftp_cmd           0
ct_flw_http_mthd     0
ct_src_ltm           0
ct_srv_dst           0
is_sm_ips_ports      0
attack_cat 

In [7]:
df_train.isnull().sum()

id                   0
dur                  1
proto                0
service              0
state                0
spkts                0
dpkts                0
sbytes               0
dbytes               0
rate                 0
sttl                 0
dttl                 0
sload                0
dload                0
sloss                0
dloss                0
sinpkt               0
dinpkt               0
sjit                 0
djit                 0
swin                 0
stcpb                0
dtcpb                0
dwin                 0
tcprtt               0
synack               0
ackdat               0
smean                0
dmean                0
trans_depth          0
response_body_len    0
ct_srv_src           0
ct_state_ttl         0
ct_dst_ltm           0
ct_src_dport_ltm     0
ct_dst_sport_ltm     0
ct_dst_src_ltm       0
is_ftp_login         0
ct_ftp_cmd           0
ct_flw_http_mthd     0
ct_src_ltm           0
ct_srv_dst           0
is_sm_ips_ports      0
attack_cat 

In [8]:
z_test =df_test['dur'].mean()
z_train = df_test['dur'].mean()
df_test['dur'].fillna(z_test,inplace=True)
df_train['dur'].fillna(z_train,inplace=True)

In [9]:
df_test.isnull().sum()

id                   0
dur                  0
proto                0
service              0
state                0
spkts                0
dpkts                0
sbytes               0
dbytes               0
rate                 0
sttl                 0
dttl                 0
sload                0
dload                0
sloss                0
dloss                0
sinpkt               0
dinpkt               0
sjit                 0
djit                 0
swin                 0
stcpb                0
dtcpb                0
dwin                 0
tcprtt               0
synack               0
ackdat               0
smean                0
dmean                0
trans_depth          0
response_body_len    0
ct_srv_src           0
ct_state_ttl         0
ct_dst_ltm           0
ct_src_dport_ltm     0
ct_dst_sport_ltm     0
ct_dst_src_ltm       0
is_ftp_login         0
ct_ftp_cmd           0
ct_flw_http_mthd     0
ct_src_ltm           0
ct_srv_dst           0
is_sm_ips_ports      0
attack_cat 

In [10]:
df_train.isnull().sum()

id                   0
dur                  0
proto                0
service              0
state                0
spkts                0
dpkts                0
sbytes               0
dbytes               0
rate                 0
sttl                 0
dttl                 0
sload                0
dload                0
sloss                0
dloss                0
sinpkt               0
dinpkt               0
sjit                 0
djit                 0
swin                 0
stcpb                0
dtcpb                0
dwin                 0
tcprtt               0
synack               0
ackdat               0
smean                0
dmean                0
trans_depth          0
response_body_len    0
ct_srv_src           0
ct_state_ttl         0
ct_dst_ltm           0
ct_src_dport_ltm     0
ct_dst_sport_ltm     0
ct_dst_src_ltm       0
is_ftp_login         0
ct_ftp_cmd           0
ct_flw_http_mthd     0
ct_src_ltm           0
ct_srv_dst           0
is_sm_ips_ports      0
attack_cat 

In [11]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 175341 entries, 0 to 175340
Data columns (total 45 columns):
 #   Column             Non-Null Count   Dtype  
---  ------             --------------   -----  
 0   id                 175341 non-null  int64  
 1   dur                175341 non-null  float64
 2   proto              175341 non-null  object 
 3   service            175341 non-null  object 
 4   state              175341 non-null  object 
 5   spkts              175341 non-null  int64  
 6   dpkts              175341 non-null  int64  
 7   sbytes             175341 non-null  int64  
 8   dbytes             175341 non-null  int64  
 9   rate               175341 non-null  float64
 10  sttl               175341 non-null  int64  
 11  dttl               175341 non-null  int64  
 12  sload              175341 non-null  float64
 13  dload              175341 non-null  float64
 14  sloss              175341 non-null  int64  
 15  dloss              175341 non-null  int64  
 16  si

In [12]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 82332 entries, 0 to 82331
Data columns (total 45 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   id                 82332 non-null  int64  
 1   dur                82332 non-null  float64
 2   proto              82332 non-null  object 
 3   service            82332 non-null  object 
 4   state              82332 non-null  object 
 5   spkts              82332 non-null  int64  
 6   dpkts              82332 non-null  int64  
 7   sbytes             82332 non-null  int64  
 8   dbytes             82332 non-null  int64  
 9   rate               82332 non-null  float64
 10  sttl               82332 non-null  int64  
 11  dttl               82332 non-null  int64  
 12  sload              82332 non-null  float64
 13  dload              82332 non-null  float64
 14  sloss              82332 non-null  int64  
 15  dloss              82332 non-null  int64  
 16  sinpkt             823

In [13]:
df_train.drop_duplicates(inplace=True)
df_test.drop_duplicates(inplace=True)

In [14]:
print(df_train.duplicated())

0        False
1        False
2        False
3        False
4        False
         ...  
82327    False
82328    False
82329    False
82330    False
82331    False
Length: 82332, dtype: bool


In [15]:
print(df_test.duplicated())

0         False
1         False
2         False
3         False
4         False
          ...  
175336    False
175337    False
175338    False
175339    False
175340    False
Length: 175341, dtype: bool


In [16]:
label_encoder = preprocessing.LabelEncoder()

df_test['proto'] = label_encoder.fit_transform(df_test['proto'])
df_test['state'] = label_encoder.fit_transform(df_test['state'])
df_test['service'] = label_encoder.fit_transform(df_test['service'])
df_test['dwin'] = label_encoder.fit_transform(df_test['dwin'])
df_test['attack_cat'] = label_encoder.fit_transform(df_test['attack_cat'])
df_train['proto'] = label_encoder.fit_transform(df_train['proto'])
df_train['state'] = label_encoder.fit_transform(df_train['state'])
df_train['service'] = label_encoder.fit_transform(df_train['service'])
df_train['dwin'] = label_encoder.fit_transform(df_train['dwin'])
df_train['attack_cat'] = label_encoder.fit_transform(df_train['attack_cat'])
df_train['attack_cat'].unique()


array([6, 7, 1, 2, 3, 0, 4, 9, 8, 5])

# split the label column from train and test data

In [17]:
df_test['label'].value_counts()

1    119341
0     56000
Name: label, dtype: int64

In [18]:
df_train['label'].value_counts()

1    45332
0    37000
Name: label, dtype: int64

In [19]:
x_test = df_test.drop('label',axis=1)
y_test = df_test['label']
x_train = df_train.drop('label' , axis=1)
y_train = df_train['label']

In [20]:
x_test

id       dur  proto  service  state  spkts  dpkts  sbytes  dbytes  \
0            1  1.359396    113        0      2      6      4     258     172   
1            2  0.649902    113        0      2     14     38     734   42014   
2            3  1.623129    113        0      2      8     16     364   13186   
3            4  1.681642    113        3      2     12     12     628     770   
4            5  0.449454    113        0      2     10      6     534     268   
...        ...       ...    ...      ...    ...    ...    ...     ...     ...   
175336  175337  0.000009    119        2      3      2      0     114       0   
175337  175338  0.505762    113        0      2     10      8     620     354   
175338  175339  0.000009    119        2      3      2      0     114       0   
175339  175340  0.000009    119        2      3      2      0     114       0   
175340  175341  0.000009    119        2      3      2      0     114       0   

                 rate  ...  ct_src_dport_ltm  ct_dst_sport_ltm  \
0           74.087490  ...                 1                 1   
1           78.473372  ...                 1                 1   
2           14.170161  ...                 1                 1   
3           13.677108  ...                 1                 1   
4           33.373826  ...                 2                 1   
...               ...  ...               ...               ...   
175336  111111.107200  ...                24                13   
175337      33.612649  ...                 1                 1   
175338  111111.107200  ...                 3                 3   
175339  111111.107200  ...                30                14   
175340  111111.107200  ...                30                16   

        ct_dst_src_ltm  is_ftp_login  ct_ftp_cmd  ct_flw_http_mthd  \
0                    1             0           0                 0   
1                    2             0           0                 0   
2                    3             0           0                 0   
3                    3             1           1                 0   
4                   40             0           0                 0   
...                ...           ...         ...               ...   
175336              24             0           0                 0   
175337               2             0           0                 0   
175338              13             0           0                 0   
175339              30             0           0                 0   
175340              30             0           0                 0   

        ct_src_ltm  ct_srv_dst  is_sm_ips_ports  attack_cat  
0                1           1                0           6  
1                1           6                0           6  
2                2           6                0           6  
3                2           1                0           6  
4                2          39                0           6  
...            ...         ...              ...         ...  
175336          24          24                0           5  
175337           1           1                0           8  
175338           3          12                0           5  
175339          30          30                0           5  
175340          30          30                0           5  

[175341 rows x 44 columns]

In [21]:
y_test

0         0
1         0
2         0
3         0
4         0
         ..
175336    1
175337    1
175338    1
175339    1
175340    1
Name: label, Length: 175341, dtype: int64

# Making train & test into array

In [22]:
x_test = np.array(x_test)
y_test = np.array(y_test)
x_train = np.array(x_train) 
y_train = np.array(y_train)

In [23]:
x_test

array([[1.00000000e+00, 1.35939575e+00, 1.13000000e+02, ...,
        1.00000000e+00, 0.00000000e+00, 6.00000000e+00],
       [2.00000000e+00, 6.49902000e-01, 1.13000000e+02, ...,
        6.00000000e+00, 0.00000000e+00, 6.00000000e+00],
       [3.00000000e+00, 1.62312900e+00, 1.13000000e+02, ...,
        6.00000000e+00, 0.00000000e+00, 6.00000000e+00],
       ...,
       [1.75339000e+05, 9.00000000e-06, 1.19000000e+02, ...,
        1.20000000e+01, 0.00000000e+00, 5.00000000e+00],
       [1.75340000e+05, 9.00000000e-06, 1.19000000e+02, ...,
        3.00000000e+01, 0.00000000e+00, 5.00000000e+00],
       [1.75341000e+05, 9.00000000e-06, 1.19000000e+02, ...,
        3.00000000e+01, 0.00000000e+00, 5.00000000e+00]])

In [24]:
y_test

array([0, 0, 0, ..., 1, 1, 1], dtype=int64)

In [25]:
x_train

array([[1.00000000e+00, 1.35939575e+00, 1.17000000e+02, ...,
        2.00000000e+00, 0.00000000e+00, 6.00000000e+00],
       [2.00000000e+00, 8.00000000e-06, 1.17000000e+02, ...,
        2.00000000e+00, 0.00000000e+00, 6.00000000e+00],
       [3.00000000e+00, 5.00000000e-06, 1.17000000e+02, ...,
        3.00000000e+00, 0.00000000e+00, 6.00000000e+00],
       ...,
       [8.23300000e+04, 0.00000000e+00, 6.00000000e+00, ...,
        1.00000000e+00, 1.00000000e+00, 6.00000000e+00],
       [8.23310000e+04, 0.00000000e+00, 6.00000000e+00, ...,
        1.00000000e+00, 1.00000000e+00, 6.00000000e+00],
       [8.23320000e+04, 9.00000000e-06, 1.17000000e+02, ...,
        1.00000000e+00, 0.00000000e+00, 6.00000000e+00]])

In [26]:
y_train

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

# Normalizing

In [27]:
scaler = StandardScaler(with_mean=False)
x_test = scaler.fit_transform(x_test)
x_train = scaler.fit_transform(x_train)



In [28]:
print (f"test shape is : {x_test.shape} ,test result shape is {y_test.shape}")

test shape is : (175341, 44) ,test result shape is (175341,)


In [29]:
print (f"train shape is : {x_train.shape} ,train result shape is {y_train.shape}")

train shape is : (82332, 44) ,train result shape is (82332,)


# NAIVE BAYES


In [30]:
model = GaussianNB()
model.fit(x_train , y_train)

GaussianNB()

In [31]:
y_pred_train_NB = model.predict(x_train)
y_pred_test_NB = model.predict(x_test)


In [32]:
acc_train = accuracy_score(y_true=y_train,y_pred=y_pred_train_NB)
rec_train = recall_score(y_true=y_train,y_pred=y_pred_train_NB)
per_train = precision_score(y_true=y_train,y_pred=y_pred_train_NB)
print (f' confusion_matrix is :\n {confusion_matrix(y_train,y_pred_train_NB)} \n accuracy is :{acc_train} \n recall is : {rec_train} \n precession is {per_train}')


 confusion_matrix is :
 [[34280  2720]
 [    0 45332]] 
 accuracy is :0.9669630277413399 
 recall is : 1.0 
 precession is 0.9433946557895613


# KNN

In [33]:
knn = KNeighborsClassifier(n_neighbors=2)
knn.fit(x_train , y_train)

KNeighborsClassifier(n_neighbors=2)

In [34]:
y_pred_train_KNN = knn.predict(x_train)
y_pred_test_KNN = knn.predict(x_test)

In [35]:
acc_train = accuracy_score(y_true=y_train,y_pred=y_pred_train_KNN)
rec_train = recall_score(y_true=y_train,y_pred=y_pred_train_KNN)
per_train = precision_score(y_true=y_train,y_pred=y_pred_train_KNN)
print (f' confusion_matrix is :\n {confusion_matrix(y_train,y_pred_train_KNN)} \n accuracy is :{acc_train} \n recall is : {rec_train} \n precession is {per_train}')

 confusion_matrix is :
 [[37000     0]
 [   99 45233]] 
 accuracy is :0.9987975513773503 
 recall is : 0.9978161122385952 
 precession is 1.0


# Decision Tree


In [36]:
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier(max_depth=8 , min_samples_split= 2 , min_samples_leaf=1)
dt.fit(x_train , y_train)

DecisionTreeClassifier(max_depth=8)

# Random forest


In [37]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=100)
rf.fit(x_train , y_train)

RandomForestClassifier()

In [38]:
y_pred_train_dt = dt.predict(x_train)
y_pred_train_rf = rf.predict(x_train)
acc_train_dt = accuracy_score(y_train,y_pred_train_dt)
acc_train_rf = accuracy_score(y_train,y_pred_train_rf)

acc_train_dt , acc_train_rf

(1.0, 1.0)

In [39]:
y_pred_test_dt = dt.predict(x_test)
y_pred_test_rf = rf.predict(x_test)
acc_test_dt = accuracy_score(y_test,y_pred_test_dt)
acc_test_rf = accuracy_score(y_test,y_pred_test_rf)

acc_test_dt , acc_test_rf

(0.6207903456692958, 0.623265522610228)

In [40]:
precision_dt = precision_score (y_test , y_pred_test_dt)
precision_rf = precision_score (y_test , y_pred_test_rf)\

precision_dt , precision_rf

(0.6602972399150743, 0.6612419052230225)

# SVM

In [41]:
from sklearn import svm

modelsvm = svm.SVC(kernel= "poly")
modelsvm.fit(x_train , y_train)

SVC(kernel='poly')

In [42]:
y_pred_train = modelsvm.predict(x_train)
y_pred_test = modelsvm.predict(x_test)


In [45]:
acctr = accuracy_score(y_true=y_train , y_pred= y_pred_train)
accte = accuracy_score(y_true=y_test , y_pred= y_pred_test)
r = recall_score(y_test , y_pred_test)
p = precision_score(y_test , y_pred_test)
acctr , accte , r , p

(0.9865908759656027, 0.895740300329073, 0.9269823447096974, 0.9204036807161755)